### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by otbe** [gastaldi/git-checkout-plugin#2]
Hi,

I was looking for a plugin thats able to fetch some sources from a Git repository and place it inside my project. Your plugin does exactly what I want 👍

Would you mind to publish it to central?

Thanks for your work 👍

**Comment by gastaldi** [comment]
Hey @otbe !

Glad you liked. Sure! I'll do it later today and let you know when it's available.

Thank you for the feedback!

**Comment by gastaldi** [comment]
git-sparse-checkout-plugin 1.0.0.Alpha1 is now available in central: https://repo1.maven.org/maven2/com/github/gastaldi/git-sparse-checkout-plugin/1.0.0.Alpha1/git-sparse-checkout-plugin-1.0.0.Alpha1.pom

Enjoy! :wink:
