### ISSUE TITLE
git-checkout-plugin fails on windows

### ISSUE THREAD

**Issue by Ribosom** [gastaldi/git-checkout-plugin#3]
Hi there,

your plugin seems pretty nice, sadly it is not working on Windows, since "rm" is not existing.
Is it possible to make the plugin operation system independent? (Maybe with java methods:
https://stackoverflow.com/questions/22918630/java-delete-file-directory-equivalent-of-linux-rm-rf-tmp-garbagedir)

[ERROR] Failed to execute goal com.github.gastaldi:git-sparse-checkout-plugin:1.0.0.Alpha1:git-checkout (default-cli) on project pkp-web: Caught IOException in mojo: Cannot run program "rm" (in directory "D:\dev\pkp\pkp-web\target"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden -> [Help 1]

**Comment by gastaldi** [comment]
Sure, totally doable. Want to provide a PR?

**Comment by gastaldi** [comment]
Done :)

**Comment by gastaldi** [comment]
1.0.0.Alpha2 is now in Maven central. Enjoy!

**Comment by Ribosom** [comment]
You were faster than me :-D,
but sadly it didn't work:

[ERROR] Failed to execute goal com.github.gastaldi:git-sparse-checkout-plugin:1.0.0.Alpha2:git-checkout (default-cli) on project pkp-web: Caught IOException in mojo: ...\.git\objects\pack\pack-8a1699ea692bff9c6d0b678a43f2e60834404792.idx -> [Help 1]

Maybe use FileUtils.forceDelete(outputDirectory.toPath().resolve(".git")); instead? (That worked for me)

**Comment by gastaldi** [comment]
Can you provide a PR with this fix then? I don't have a Windows VM to test it unfortunately :(

**Comment by Ribosom** [comment]
I will do it. However, I can't test for Unix, so would be good if you test it, too. :-)

**Comment by gastaldi** [comment]
Sure, I should really set up some CI using Github Actions in this repository :)

**Comment by gastaldi** [comment]
Thanks, I'll release 1.0.0.Alpha3 in some hours

**Comment by gastaldi** [comment]
1.0.0.Alpha3 is now in Central. Enjoy!
